jobs:
- job: release
  variables:
    imageName: glaux/clang-azure-devops
  pool:
    vmImage: 'ubuntu-16.04'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  steps:
    - task: Docker@1
      displayName: Build image
      inputs:
        command: build
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: glaux-registry
        dockerFile: Dockerfile
        imageName: $(imageName)
    - task: Docker@1
      displayName: Push image
      inputs:
        command: push
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: glaux-registry
        imageName: $(imageName)
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master