trigger:
  branches:
    include:
      - master
jobs:
- job: release
  variables:
    imageName: glaux/clang-azure-devops
  strategy:
    matrix:
      xenial:
        dist: xenial
        baseImage: ubuntu:xenial
        imageTags: |
          xenial
          latest
      bionic:
        dist: bionic
        baseImage: glaux/ubuntu:bionic
        imageTags: |
          bionic
      focal:
        dist: focal
        baseImage: glaux/ubuntu:focal
        imageTags: |
          focal
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageName)
        tags: $(imageTags)
        arguments: --build-arg BASE_IMAGE=$(baseImage) --build-arg DIST=$(dist)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: glaux-registry
        tags: $(imageTags)
schedules:
- cron: "0 4 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true